# change the followings to match your Github username and repo name
baseurl: "" # the name of your github repo
url: "https://akhsim.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Misha"
description: Misha Nguyen's Personal Website

# color theme for links
theme-color: stone # indigo|yellow|pink|green|stone|

# homepage information
author: Misha Nguyen
author-bio: Software Developer/ Cyclist/ Thinker  # change to false to hide
author-image: byJamesLayh.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About Me
  permalink: about
- text: Blog
  permalink: blog
- text: Tags
  permalink: tag
## TODO: Consider re-organising posts into Notes and Posts
# - text: Notes
#   permalink: notes

# use false to turn off any social media links
twitter: false
facebook: false
instagram: https://www.instagram.com/mishkanguyen/
github: https://github.com/akhsim
linkedin: https://www.linkedin.com/in/mishkaquangnguyen/
medium: false
google-scholar: false
email: false

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
